export const documents = [
  {
    id: "1D",
    name: "Mozilla Developer Network",
    url: "https://developer.mozilla.org/en-US/",
    description: "Documentacion sobre JavaScript",
  },
  {
    id: "2D",
    name: "W3schools",
    url: "https://www.w3schools.com/default.asp",
    description: "Documentacion sobre HTML, CSS y JavaScript",
  },
  {
    id: "3D",
    name: "React JS",
    url: "https://reactjs.org/",
    description: "Documentacion sobre React",
  },
  {
    id: "4D",
    name: "Sequelize",
    url: "https://sequelize.org/docs/v6/",
    description: "Documentacion sobre Sequelize",
  },
  {
    id: "5D",
    name: "Npm",
    url: "https://www.npmjs.com/",
    description: "Biblioteca de modulos",
  },
  {
    id: "6D",
    name: "Node JS",
    url: "https://nodejs.org/en/docs/",
    description: "Documentacion sobre Node",
  },
  {
    id: "7D",
    name: "Express",
    url: "https://expressjs.com/",
    description: "Documentacion sobre Express",
  },
  {
    id: "8D",
    name: "MySQL",
    url: "https://dev.mysql.com/doc/",
    description: "Documentacion sobre MySQL",
  },
  {
    id: "9D",
    name: "PostgreSQL",
    url: "https://www.postgresql.org/docs/",
    description: "Documentacion sobre PostgreSQL",
  },
  {
    id: "10D",
    name: "Git",
    url: "https://git-scm.com/docs",
    description: "Documentacion sobre Git",
  },
  {
    id: "11D",
    name: "Sass",
    url: "https://sass-lang.com/documentation/",
    description: "Documentacion sobre Sass",
  },
  {
    id: "12D",
    name: "CSS Tricks",
    url: "https://css-tricks.com/guides/",
    description: "Guias sobre CSS",
  },
  {
    id: "13D",
    name: "React Router",
    url: "https://reactrouter.com/en/main",
    description: "Documentacion sobre React Router",
  },
  {
    id: "14D",
    name: "CSS Reference",
    url: "https://cssreference.io/",
    description: "Referencias de CSS",
  },
  {
    id: "15D",
    name: "CSS Triggers",
    url: "https://csstriggers.com/",
    description: "Informacion sobre los selectores del DOM",
  },
  {
    id: "16D",
    name: "Jest",
    url: "https://jestjs.io/",
    description: "Documentacion sobre Jest",
  },
  {
    id: "17D",
    name: "Redux",
    url: "https://redux.js.org/",
    description: "Documentacion sobre Redux",
  },
];
export const resources = [
  {
    id: "1R",
    name: "Google Fonts",
    url: "https://fonts.google.com/",
    description: "Fuentes",
  },
  {
    id: "2R",
    name: "Adobe Color",
    url: "https://color.adobe.com/es/create/color-wheel",
    description: "Paletas de colores",
  },
  {
    id: "3R",
    name: "Fontawesome",
    url: "https://fontawesome.com/",
    description: "Iconos",
  },
  {
    id: "4R",
    name: "Hexcolor",
    url: "https://hexcolor.co/generate-color-gradient",
    description: "Gradientes",
  },
  {
    id: "5R",
    name: "Bootstrap",
    url: "https://getbootstrap.com/",
    description: "Framework CSS",
  },
  {
    id: "6R",
    name: "CSS Generator",
    url: "https://cssgenerator.org/",
    description: "Generador de CSS",
  },
  {
    id: "7R",
    name: "Flaticon",
    url: "https://www.flaticon.com/free-icons/css",
    description: "Iconos",
  },
  {
    id: "8R",
    name: "CSS.gg",
    url: "https://css.gg/",
    description: "Iconos",
  },
  {
    id: "9R",
    name: "Pexels",
    url: "https://www.pexels.com/es-es/",
    description: "Biblioteca de imagenes",
  },
  {
    id: "10R",
    name: "CSS Matic",
    url: "https://www.cssmatic.com/",
    description: "Generador de CSS",
  },
  {
    id: "11R",
    name: "Color Code",
    url: "https://htmlcolorcodes.com/es/nombres-de-los-colores/",
    description: "Paletas de colores",
  },
  {
    id: "12R",
    name: "Specificity",
    url: "https://specificity.keegan.st/",
    description: "Especificidad de CSS",
  },
  {
    id: "13R",
    name: "Unsplash",
    url: "https://unsplash.com/es",
    description: "Biblioteca de imagenes",
  },
  {
    id: "14R",
    name: "Canva Generator",
    url: "https://www.canva.com/colors/color-palette-generator/",
    description: "Paletas de colores",
  },
  {
    id: "15R",
    name: "Remove Bg",
    url: "https://www.remove.bg/es",
    description: "Quitar fondo a imagenes",
  },
  {
    id: "16R",
    name: "Toptal",
    url: "https://www.toptal.com/designers/subtlepatterns/",
    description: "Patrones CSS",
  },
  {
    id: "17R",
    name: "Flatiucolors",
    url: "https://flatuicolors.com/",
    description: "Paletas de colores",
  },
  {
    id: "18R",
    name: "Boxicons",
    url: "https://boxicons.com/",
    description: "Iconos",
  },
  {
    id: "19R",
    name: "Webgradients",
    url: "https://webgradients.com/",
    description: "Gradientes",
  },
  {
    id: "20R",
    name: "Smooth",
    url: "https://smooth.ie/blogs/news/svg-wavey-transitions-between-sections",
    description: "Generador de waves",
  },
  {
    id: "21R",
    name: "Can I Use",
    url: "https://caniuse.com/",
    description: "Verificar soporte en navegadores",
  },
  {
    id: "22R",
    name: "Undraw",
    url: "https://undraw.co/illustrations",
    description: "Imagenes SVG",
  },
  {
    id: "23R",
    name: "Normalize.css",
    url: "https://necolas.github.io/normalize.css/",
    description: "Remover CSS por defecto",
  },
  {
    id: "24R",
    name: "SVGporn",
    url: "https://svgporn.com/",
    description: "Iconos",
  },
  {
    id: "25R",
    name: "Clippy",
    url: "https://bennettfeely.com/clippy/",
    description: "Clip-Path",
  },
  {
    id: "26R",
    name: "Cubic Bezier",
    url: "https://cubic-bezier.com/#0,0,1,1",
    description: "Transiciones CSS",
  },
  {
    id: "27R",
    name: "Magic Pattern",
    url: "https://www.magicpattern.design/tools/css-backgrounds",
    description: "Patrones",
  },
  {
    id: "28R",
    name: "CSS Gradient",
    url: "https://cssgradient.io/",
    description: "Gradientes",
  },
  {
    id: "29R",
    name: "Tinypng",
    url: "https://tinypng.com/",
    description: "Compresor de imagenes",
  },
  {
    id: "30R",
    name: "Getwaves",
    url: "https://getwaves.io/",
    description: "Generador de waves",
  },
  {
    id: "31R",
    name: "UIgradients",
    url: "https://uigradients.com/#Shore",
    description: "Gradientes",
  },
  {
    id: "32R",
    name: "Figma",
    url: "https://www.figma.com/",
    description: "Editor",
  },
];
